### Get products
GET http://localhost:3000/api/v1/products

### Get product by id
GET http://localhost:3000/api/v1/products/b0b6b90f-2c71-4bdd-b3a3-8f1f14ff0d11

### Create product
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name":"New product",
  "price": 300,
  "image": "https://picsum.photos/seed/EtqtXY/2329/2213?blur=8"
}

### Partial update product
PATCH http://localhost:3000/api/v1/products/b0b6b90f-2c71-4bdd-b3a3-8f1f14ff0d18
Content-Type: application/json

{
  "name": "Updated product",
  "price": 500
}

### Delete product
DELETE http://localhost:3000/api/v1/products/8f5628b4-3e64-48d8-8853-8e2f8d3ffeee
